# Generated by Django 4.2.18 on 2025-09-15 23:53

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=20, unique=True, verbose_name='RUT')),
                ('first_name', models.CharField(max_length=80, verbose_name='Nombres')),
                ('last_name', models.CharField(max_length=80, verbose_name='Apellidos')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Fecha de nacimiento')),
                ('sex', models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro / Prefiere no decir')], max_length=1, verbose_name='Sexo')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='Teléfono')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='SpeechAudiometry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('ear', models.CharField(choices=[('R', 'Oído Derecho'), ('L', 'Oído Izquierdo'), ('B', 'Binaural / Campo libre')], default='R', max_length=1)),
                ('srt', models.IntegerField(blank=True, null=True, verbose_name='SRT/SDT (dB HL)')),
                ('wrs_percent', models.IntegerField(blank=True, null=True, verbose_name='Reconocimiento de Palabras (%)')),
                ('wrs_level_db', models.IntegerField(blank=True, null=True, verbose_name='Nivel de presentación (dB HL)')),
                ('notes', models.CharField(blank=True, max_length=200, verbose_name='Notas')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='speech_tests', to='core.patient')),
            ],
            options={
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='LDL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('ear', models.CharField(choices=[('R', 'Oído Derecho'), ('L', 'Oído Izquierdo'), ('B', 'Binaural / Campo libre')], default='R', max_length=1)),
                ('ldl_500', models.IntegerField(blank=True, null=True)),
                ('ldl_1k', models.IntegerField(blank=True, null=True)),
                ('ldl_2k', models.IntegerField(blank=True, null=True)),
                ('ldl_4k', models.IntegerField(blank=True, null=True)),
                ('notes', models.CharField(blank=True, max_length=200)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ldl_tests', to='core.patient')),
            ],
            options={
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Audiogram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('exam_type', models.CharField(choices=[('TONAL', 'Tonal (Aérea/Ósea)'), ('FIELD', 'Campo Libre'), ('PLAY', 'Audiometría Infantil/Play'), ('HF', 'Alta Frecuencia')], default='TONAL', max_length=10)),
                ('transducer', models.CharField(choices=[('SUPRA', 'Supraaural'), ('CIRCUM', 'Circumaural'), ('INSERT', 'Insert'), ('SPEAKER', 'Parlante')], default='INSERT', max_length=10)),
                ('masking_used', models.BooleanField(default=False, verbose_name='Se usó enmascaramiento')),
                ('comments', models.TextField(blank=True, verbose_name='Comentarios')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audiograms', to='core.patient')),
            ],
            options={
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Anamnesis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('main_complaint', models.TextField(blank=True, verbose_name='Motivo de consulta')),
                ('hearing_loss', models.BooleanField(default=False, verbose_name='Hipoacusia')),
                ('tinnitus', models.BooleanField(default=False, verbose_name='Acúfenos / Tinnitus')),
                ('otalgia', models.BooleanField(default=False, verbose_name='Otalgia')),
                ('otorrhea', models.BooleanField(default=False, verbose_name='Otorrhea')),
                ('vertigo', models.BooleanField(default=False, verbose_name='Vértigo')),
                ('noise_exposure', models.BooleanField(default=False, verbose_name='Exposición a ruido')),
                ('hearing_aids', models.BooleanField(default=False, verbose_name='Uso de audífonos')),
                ('medication', models.TextField(blank=True, verbose_name='Medicamentos / Ototóxicos')),
                ('vertigo_type', models.CharField(blank=True, max_length=120, verbose_name='Tipo de vértigo (si aplica)')),
                ('vertigo_duration', models.CharField(blank=True, max_length=120, verbose_name='Duración de crisis')),
                ('vertigo_triggers', models.CharField(blank=True, max_length=200, verbose_name='Desencadenantes')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anamneses', to='core.patient')),
            ],
            options={
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Threshold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ear', models.CharField(choices=[('R', 'Oído Derecho'), ('L', 'Oído Izquierdo'), ('B', 'Binaural / Campo libre')], max_length=1)),
                ('pathway', models.CharField(choices=[('AC', 'Aérea'), ('BC', 'Ósea')], default='AC', max_length=2)),
                ('symbol', models.CharField(blank=True, max_length=2, verbose_name='Símbolo')),
                ('f_250', models.IntegerField(blank=True, null=True)),
                ('f_500', models.IntegerField(blank=True, null=True)),
                ('f_1000', models.IntegerField(blank=True, null=True)),
                ('f_2000', models.IntegerField(blank=True, null=True)),
                ('f_3000', models.IntegerField(blank=True, null=True)),
                ('f_4000', models.IntegerField(blank=True, null=True)),
                ('f_6000', models.IntegerField(blank=True, null=True)),
                ('f_8000', models.IntegerField(blank=True, null=True)),
                ('audiogram', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thresholds', to='core.audiogram')),
            ],
            options={
                'unique_together': {('audiogram', 'ear', 'pathway')},
            },
        ),
    ]
